import { CampaignPlanActions } from "@/components/marketing/campaign-plan-actions"
import { CampaignPlanner } from "@/components/marketing/campaign-planner"
import { MarketingPageHeader } from "@/components/marketing/marketing-page-header"
import { requireMarketingAdminPage } from "@/lib/auth/marketing"
import { MarketingRepository } from "@/lib/marketing/repositories/marketing-repository"
import { createServerSupabaseClient } from "@/lib/supabase/server"

type Props = { searchParams: Promise<{ selected?: string }> }

export default async function CampaignsPage({ searchParams }: Props) {
  await requireMarketingAdminPage()
  const [campaigns, parameters, supabase] = await Promise.all([MarketingRepository.listCampaigns(), searchParams, createServerSupabaseClient()])
  const { data } = await supabase.from("properties").select("id, name, location, cover_image").order("created_at", { ascending: false })
  const selected = parameters.selected ? campaigns.find(campaign => campaign.id === parameters.selected) : undefined
  return <><MarketingPageHeader pathname="/marketing/campaigns" eyebrow="One-click campaigns" title="Create a balanced plan before you spend on generation." description="Plan property rotation, formats and cadence from your live inventory. Your explicit plan approval creates drafts only — it never approves or publishes any content." /><main className="mx-auto w-full max-w-7xl space-y-8 p-4 sm:p-6 lg:p-8">{selected && <section className="rounded-2xl border bg-card p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold tracking-[0.14em] text-primary uppercase">Campaign plan ready</p><h2 className="mt-1 text-xl font-semibold">{selected.title}</h2><p className="mt-1 text-sm text-muted-foreground">{selected.durationDays} days · {selected.plan.length} planned items · {selected.objective}</p></div>{selected.status === "plan_ready" && <CampaignPlanActions campaignId={selected.id} />}</div><div className="mt-5 overflow-hidden rounded-xl border">{selected.plan.map((item, index) => <div key={`${item.propertyId}-${index}`} className="flex gap-4 border-b p-3 text-sm last:border-b-0"><span className="w-20 shrink-0 font-semibold text-muted-foreground">Day {index + 1}</span><span className="min-w-0 flex-1"><span className="font-semibold">{item.propertyName}</span><span className="block text-muted-foreground">{item.contentType.replaceAll("_", " ")} · {item.hook}</span></span><time className="hidden text-muted-foreground sm:block">{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short" }).format(new Date(item.plannedFor))}</time></div>)}</div></section>}<CampaignPlanner properties={(data ?? []).map(property => ({ id: property.id, name: property.name, location: property.location ?? "", coverImage: property.cover_image ?? undefined }))} />{campaigns.length > 0 && <section><h2 className="mb-4 text-lg font-semibold">Campaign history</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{campaigns.map(campaign => <article key={campaign.id} className="rounded-2xl border bg-card p-5"><p className="text-xs font-semibold tracking-[0.14em] text-primary uppercase">{campaign.status.replaceAll("_", " ")}</p><h3 className="mt-2 font-semibold">{campaign.title}</h3><p className="mt-1 text-sm text-muted-foreground">{campaign.plan.length} planned posts · {campaign.durationDays} days</p></article>)}</div></section>}</main></>
}
